# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73ce97b47a137259a4b1eb6861866129a36b595cdd7119cfa520645421767128b9e76cc2741bf21ef6de343174d3e6969b561a4cc2c86cfac1a2637c3c0cbfee

test:
  secret_key_base: eec4fcd2e6596749f5d1c30d25dec55a63b8577678285ac31b4af0aa07dbe998a05fb75f8330d0f448c802a8e98c05671988ec4b81a82b4854da2f0fecfcadb5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
